[package]
name = "split_server"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
utils = { path = "../utils" }
tokio = { workspace = true, features = ["rt-multi-thread"] }
anyhow = { workspace = true }
