trigger: [ "main" ]
pr: [ "main" ]

variables:
  RUSTFLAGS: -Dwarnings
  RUST_VERSION: 1.64.0

stages:
  - stage: Setup
    jobs:
      - job:
        steps:
          - template: azure-install-rust.yml
            parameters:
              rust_version: $(RUST_VERSION)

          - template: azure-install-sccache.yml

  #  - stage: Lint
  #    dependsOn: setup
  #    jobs:
  #      - template: azure-lint.yml
  #        parameters:
  #          name: lint_crates
  #          rust: $(RUST_VERSION)
  #          displayName: All crates

  #  - stage: Test
  #    #    dependsOn: Lint
  #    jobs:
  #      - template: azure-test-stable.yml
  #        parameters:
  #          rust: $(RUST_VERSION)
  #          displayName: All crates


  #  - stage: autobahnclient
  #    displayName: Autobahn Client
  #    #    dependsOn: Lint
  #    jobs:
  #      - template: azure-autobahn-client.yml
  #        parameters:
  #          rust: $(RUST_VERSION)

  - stage: autobahnserver
    displayName: Autobahn Server
    #    dependsOn: Lint
    jobs:
      - template: azure-autobahn-server.yml
        parameters:
          rust: $(RUST_VERSION)
