trigger: [ "main" ]
pr: [ "main" ]

variables:
  RUSTFLAGS: -Dwarnings
  RUST_VERSION: 1.64.0

stages:
  - stage: setup
    jobs:
      - job:
        steps:
          - template: azure-install-rust.yml
            parameters:
              rust_version: $(RUST_VERSION)

          - template: azure-install-sccache.yml

  - stage: lint
    dependsOn: setup
    jobs:
      - template: .azure/azure-lint.yml
        parameters:
          name: lint_crates
          rust: $(RUST_VERSION)
          displayName: All crates

  - stage: test
    dependsOn: Lint
    jobs:
      - template: .azure/azure-test-stable.yml
        parameters:
          name: test_crates
          rust: $(RUST_VERSION)
          displayName: All crates
