jobs:
  - job: autobahnserver
    displayName: Autobahn Server
    timeoutInMinutes: 180
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - script: cargo run --bin split_server --release
        env:
          RUST_BACKTRACE: 1
        workingDirectory: $(Build.SourcesDirectory)