jobs:
  - job: test
    displayName: Test
    strategy:
      matrix:
        Linux:
          vmImage: ubuntu-22.04
        MacOS:
          vmImage: macOS-12
        Windows:
          vmImage: windows-2019
    pool:
      vmImage: $(vmImage)

    steps:
      - script: cargo test --verbose --all-features --workspace --lib --tests
        env:
          RUST_BACKTRACE: 1
        displayName: cargo test --lib --tests
        workingDirectory: $(Build.SourcesDirectory)