[package]
name = "utils"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
ratchet_rs = { path = "../.." }
tokio = { workspace = true, features = ["process", "macros", "time"] }
anyhow = { workspace = true }
serde_json = { workspace = true }
